name_regex="^[a-zA-Z]*$"
state_regex="^[a-z A-Z]*$"
email_regex = "^[a-zA-Z0-9]+(?:\.[a-zA-Z0-9]+)*@[a-zA-Z0-9]+(?:\.[a-zA-Z0-9]+){1,2}$"
password_regex="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$"
contact_no_regex="^[0-9]{10}$"
euin_regex="^E[0-9]{6}$"
aadhar_number_regex="^[0-9]{12}$"
pan_no_regex="^([A-Z]){5}([0-9]){4}([A-Z]){1}?$"
biling_adress_regex="^[a-zA-Z0-9 ,-./]+$"
arn_no_regex="^ARN-[0-9]{6}$"
member_code_regex="^[0-9]{5}$"
companey_name_regex="^.{0,50}$"
gst_in_regex="^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$"
ans_regex="^[a-zA-Z]+$"